name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        id: build-mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
        env:
          # Ép biến môi trường vào thẳng bước build
          Geode_DIR: ${{ github.workspace }}/geode-sdk
          GEODE_SDK: ${{ github.workspace }}/geode-sdk
