name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Build cho từng nền tảng trong matrix
          target: ${{ matrix.config.target }}
          # Kết hợp tất cả vào một file .geode duy nhất (tiện cực kỳ!)
          combine: true