name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # BƯỚC 1: Phải cài đặt SDK trước
      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode@v2

      # BƯỚC 2: Sau đó mới chạy lệnh build
      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          path: ./  # Nếu CMakeLists.txt nằm ở ngoài cùng
          combine: true
